# Generated by Django 3.2.18 on 2023-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='urls',
            field=models.TextField(default=''),
        ),
    ]
